// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%jOqQPOOOxQPO'#CbO}QPO'#CaOOQO'#Ch'#ChO!SQPO'#CgOOQO'#Cm'#CmO!SQPO'#ClOOQO'#C`'#C`O!XQPO'#C_QOQPOOOOQO,58|,58|OOQO'#Cd'#CdO!SQPO,58{O!jQPO,59RO!oQPO,59WOYQPO'#CnO!zQPO,58yO#]QPO1G.gOOQO'#Ci'#CiO#eQQO1G.mOOQO'#Cj'#CjO#jQPO1G.rOOQO,59Y,59YOOQO-E6l-E6lOOQO'#Ce'#CeO#wQPO7+$RO!oQPO7+$XO#|QPO7+$^OOQO'#Cf'#CfOOQO<<Gm<<GmO#jQPO<<GsOOQO'#Ck'#CkOOQO<<Gx<<GxO#|QPOAN=_OOQOG22yG22y",
  stateData: "$X~OeOSPOS~OfPOjROkROlROuTOvTOwTO~OcRP~PYOVYO~OgZO~OfPO~Ox_OcRXrRXsRXtRX~OmbO~OodOpdOqdO~Ox_OcRarRasRatRa~OhhOihO~OnjO~OrRPsRPtRP~PYOVlO~OroOsoOtoO~O",
  goto: "#WcPPPdmu{P![!_!bu!e!k!n!tu!z#QQXOQkeRqnUWOenRf_XVO_enWQO_enQ]SQ^URa[R[QRiaRmiXSO_enRc]Qe^RnjQpkRrqXUO_enQ`WRg`",
  nodeNames: "⚠ Comment WHILE Program Statement Assignment Variable Number AssignOperator Operator Constant WhileStatement While NotEqual Do End LoopStatement Loop",
  maxTerm: 40,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: ")j~RdXY!aYZ!apq!aqr!o{|!z}!O#P!P!Q#U!Q!R#s!R![#}![!]$V!]!^$b!f!g$g!g!h$z!n!o%k!y!z&h#W#X'q#X#Y'|#`#a(_#k#l(v#l#m)e~!fRe~XY!aYZ!apq!a~!rP!_!`!u~!zOm~~#POh~~#UOi~~#XP!P!Q#[~#aSP~OY#[Z;'S#[;'S;=`#m<%lO#[~#pP;=`<%l#[R#zPnQVP!Q![#}P$SPVP!Q![#}~$YP!_!`$]~$bOg~~$gOx~~$jQ!q!r$p#c#d$u~$uOo~~$zOq~~$}Q!p!q%T#b#c%`~%WP!f!g%Z~%`Or~~%cP#W#X%f~%kOt~~%nQ!q!r%t#c#d&V~%wP!q!r%z~%}P!r!s&Q~&VOu~~&YP#c#d&]~&`P#d#e&c~&hOw~~&kQ!j!k&q#[#]'Y~&tP!k!l&w~&zP!n!o&}~'QP!g!h'T~'YOj~~']P#]#^'`~'cP#`#a'f~'iP#X#Y'l~'qOl~~'tP#c#d'w~'|Op~~(PP#b#c(S~(VP#W#X(Y~(_Os~~(bP#c#d(e~(hP#c#d(k~(nP#d#e(q~(vOv~~(yP#[#](|~)PP#]#^)S~)VP#`#a)Y~)]P#X#Y)`~)eOk~~)jOf~",
  tokenizers: [0, 1],
  topRules: {"WHILE":[0,2]},
  tokenPrec: 0
})
