// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  WHILE = 2,
  Program = 3,
  Statement = 4,
  Assignment = 5,
  Variable = 6,
  Number = 7,
  AssignOperator = 8,
  Operator = 9,
  Constant = 10,
  WhileStatement = 11,
  While = 12,
  NotEqual = 13,
  Do = 14,
  End = 15,
  LoopStatement = 16,
  Loop = 17
