// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Programm = 2,
  Zeile = 3,
  Marke = 4,
  Anweisung = 5,
  CMD_VALUE = 6,
  VALUE = 7,
  KONSTANTE = 8,
  Number = 9,
  DIREKT = 10,
  INDIREKT = 11,
  CMD_ZIEL = 12,
  Ziel = 13,
  Word = 14,
  CMD_END = 15,
  NewLine = 16
