// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Programm = 2,
  Zeile = 3,
  Marke = 4,
  Anweisung = 5,
  CMD_STORE = 6,
  DIREKT = 7,
  Number = 8,
  INDIREKT = 9,
  CMD_VALUE = 10,
  VALUE = 11,
  KONSTANTE = 12,
  CMD_ZIEL = 13,
  Ziel = 14,
  Word = 15,
  CMD_END = 16,
  NewLine = 17
