// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$OOYQPOOOOQO'#Cb'#CbOOQO'#Ch'#ChOOQO'#Ck'#CkO!TQPO'#CaO!`QQO'#CaOOQO'#Ca'#CaOOQO'#C_'#C_O!eQPO'#C_Q#VQPOOO#[QPO'#CdOOQO'#Cf'#CfO#aQPO'#CgOOQO'#Cc'#CcOOQO,58{,58{OOQO'#Ci'#CiOOQO,58y,58yOYQPO'#CmQ#VQPOOOOQO,59O,59OOOQO,59R,59ROOQO,59X,59XOOQO-E6k-E6k",
  stateData: "#i~OdOSPOS~OSWOePOfPOgPOhPOiPOjPOmQOnQOoQOpRO`RPbRP~OXZOkYOl[O~O^_O~OePOfPOgPOhPOiPOjPOmQOnQOoQOpRO~O`aO~OXcO~OXdO~O^X~",
  goto: "!`bPPPcPipuxPxx{!QP!TP!YQXOReaSVOaR`WVSOWaR^SR]SVTOWaR^TVUOWaQbXRfb",
  nodeNames: "⚠ Comment Programm Zeile Marke Anweisung CMD_VALUE VALUE KONSTANTE Number DIREKT INDIREKT CMD_ZIEL Ziel Word CMD_END NewLine",
  maxTerm: 32,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "8b~RfYZ!gpq!lst!tz{!y!P!Q#O!Q![#m!c!d#u!d!f$a!f!g%|!g!h'j!h!i$a!i!j)W!j!l$a!l!m+`!m!n$a!n!o0v!o!p2{!p!u$a!u!v4i!v!}$a#R#S$a#T#o$a~!lO`~~!qPd~pq!l~!yOk~~#OOl~~#RP!P!Q#U~#ZSP~OY#UZ;'S#U;'S;=`#g<%lO#U~#jP;=`<%l#U~#rPX~!Q![#mR#zV^Q!Q![$a![!]$u!c!f$a!f!g$z!g!}$a#R#S$a#T#o$aR$fT^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aP$zOSPR%PV^Q!Q![$a![!]$u!c!f$a!f!g%f!g!}$a#R#S$a#T#o$aR%mTgP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR&RV^Q!Q![$a![!]$u!c!k$a!k!l&h!l!}$a#R#S$a#T#o$aR&mV^Q!Q![$a![!]$u!c!x$a!x!y'S!y!}$a#R#S$a#T#o$aR'ZTjP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR'oV^Q!Q![$a![!]$u!c!p$a!p!q(U!q!}$a#R#S$a#T#o$aR(ZV^Q!Q![$a![!]$u!c!f$a!f!g(p!g!}$a#R#S$a#T#o$aR(wTpP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR)]V^Q!Q![$a![!]$u!c!q$a!q!r)r!r!}$a#R#S$a#T#o$aR)wV^Q!Q![$a![!]$u!c!v$a!v!w*^!w!}$a#R#S$a#T#o$aR*cV^Q!Q![$a![!]$u!c!q$a!q!r*x!r!}$a#R#S$a#T#o$aR+PTmP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR+eW^Q!Q![$a![!]$u!c!p$a!p!q+}!q!|$a!|!}.n#R#S$a#T#o$aR,SU^Q!Q![$a![!]$u!c!|$a!|!},f#R#S$a#T#o$aR,kV^Q!Q![$a![!]$u!c!g$a!g!h-Q!h!}$a#R#S$a#T#o$aR-VV^Q!Q![$a![!]$u!c!t$a!t!u-l!u!}$a#R#S$a#T#o$aR-qV^Q!Q![$a![!]$u!c!q$a!q!r.W!r!}$a#R#S$a#T#o$aR._ToP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR.sV^Q!Q![$a![!]$u!c!g$a!g!h/Y!h!}$a#R#S$a#T#o$aR/_V^Q!Q![$a![!]$u!c!t$a!t!u/t!u!}$a#R#S$a#T#o$aR/yV^Q!Q![$a![!]$u!c!q$a!q!r0`!r!}$a#R#S$a#T#o$aR0gTnP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR0{V^Q!Q![$a![!]$u!c!q$a!q!r1b!r!}$a#R#S$a#T#o$aR1gU^Q!Q![$a![!]$u!c!d1y!d!}$a#R#S$a#T#o$aR2OV^Q!Q![$a![!]$u!c!f$a!f!g2e!g!}$a#R#S$a#T#o$aR2lTeP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR3QV^Q!Q![$a![!]$u!c!w$a!w!x3g!x!}$a#R#S$a#T#o$aR3lV^Q!Q![$a![!]$u!c!n$a!n!o4R!o!}$a#R#S$a#T#o$aR4YTiP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR4nW^Q!Q![$a![!]$u!c!v$a!v!w5W!w!x7`!x!}$a#R#S$a#T#o$aR5]V^Q!Q![$a![!]$u!c!q$a!q!r5r!r!}$a#R#S$a#T#o$aR5wV^Q!Q![$a![!]$u!c!t$a!t!u6^!u!}$a#R#S$a#T#o$aR6cV^Q!Q![$a![!]$u!c!g$a!g!h6x!h!}$a#R#S$a#T#o$aR7PTfP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$aR7eV^Q!Q![$a![!]$u!c!d$a!d!e7z!e!}$a#R#S$a#T#o$aR8RThP^Q!Q![$a![!]$u!c!}$a#R#S$a#T#o$a",
  tokenizers: [0, 1],
  topRules: {"Programm":[0,2]},
  tokenPrec: 114
})
