// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Formel = 1,
  Term = 2,
  BinaryExpression = 3,
  Klammerausdruck = 4,
  Wert = 5,
  Zahl = 6,
  Number = 7,
  Word = 8,
  Functionname = 9,
  Bezug = 10,
  Bereich = 11
