// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Formel = 1,
  Term = 2,
  BinaryExpression = 3,
  Plus = 4,
  Mal = 5,
  Minus = 6,
  Geteilt = 7,
  Hoch = 8,
  Klammerausdruck = 9,
  Wert = 10,
  Zahl = 11,
  Number = 12,
  Word = 13,
  Functionname = 14,
  Bezug = 15,
  Bereich = 16
