// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%dQVQPOOO[QPOOQmQPOOO[QPO'#C`O!OQPO'#CbOOQO'#Ca'#CaO!mQQO'#CaO!rQPO'#CaO!wQPO'#C^OOQO'#C^'#C^O[QPO,58yO[QPO,58yO[QPO,58yO[QPO,58yO#fQPO,58zO#mQPO,58|O#rQPO,58{O[QPO,58{O#wQPO,59RO$bQPO1G.eO$lQPO1G.eO$vQPO1G.eOOQO1G.e1G.eOOQO1G.f1G.fOOQO1G.h1G.hOOQO1G.g1G.gO%bQPO1G.gOOQO1G.m1G.mO[QPO'#ChO%lQPO7+$ROOQO7+$R7+$RO%tQPO,59SOOQO-E6f-E6fOOQO<<Gm<<Gm",
  stateData: "&R~O_OS~O`PO~OVSOXVOYWOfROiUO~OaYObZOc[OdZOe]O~Oh_O]UXaUXbUXcUXdUXeUXgUXjUX~OW`O~OfaO~OkbO]QXaQXbQXcQXdQXeQXgQXjQX~OggO~PmOVhO~OiiO~OYkO~Oc[Oe]O]RiaRigRijRi~ObZOdZO~P#|ObRidRi~P#|Oe]O]RiaRibRicRidRigRijRi~OgnOjlO~PmOgqOjlO~Og[aj[a~PmOWV~",
  goto: "!b]PP^vvv!QPPPPv![QQPQ^RQcYQdZQe[Qf]QjaRolaXPRYZ[]alaTPRYZ[]alQmjRpm",
  nodeNames: "⚠ Formel Term BinaryExpression Klammerausdruck Wert Zahl Number Word Functionname Bezug Bereich",
  maxTerm: 27,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ")k~RiXY!ppq!prs!{xy#Qyz#Vz{#[{|#a|}#f}!O#k!P!Q#p!Q![#u![!]#}!]!^$S!_!`$X!c!}$^#Q#R(k#R#S(p#T#o$^%[%](p%n%o(p%t%u(p%w%x(p%|%}(p&`&a(p&f&g(p~!uQ_~XY!ppq!p~#QOi~~#VOf~~#[Og~~#aOb~~#fOa~~#kOh~~#pOc~~#uOd~~#zPV~!Q![#u~$SOk~~$XOj~~$^O`~R$c[WQ!O!P%X!Q![&P!c!}'q#R#S'q#T#o'q%[%]'q%n%o'q%t%u'q%w%x'q%|%}'q&`&a'q&f&g'qP%^ZXP!Q![%X!c!}%X#R#S%X#T#o%X%[%]%X%n%o%X%t%u%X%w%x%X%|%}%X&`&a%X&f&g%XR&WZYPWQ!Q![&P!c!}&y#R#S&y#T#o&y%[%]&y%n%o&y%t%u&y%w%x&y%|%}&y&`&a&y&f&g&yQ'OZWQ!Q![&y!c!}&y#R#S&y#T#o&y%[%]&y%n%o&y%t%u&y%w%x&y%|%}&y&`&a&y&f&g&yR'xZXPWQ!Q!['q!c!}'q#R#S'q#T#o'q%[%]'q%n%o'q%t%u'q%w%x'q%|%}'q&`&a'q&f&g'q~(pOe~R(u[WQ!O!P%X!Q![&y!c!}'q#R#S'q#T#o'q%[%]'q%n%o'q%t%u'q%w%x'q%|%}'q&`&a'q&f&g'q",
  tokenizers: [0, 1],
  topRules: {"Formel":[0,1]},
  tokenPrec: 230
})
